name: ci

on:
  pull_request:
    branches: '*'
  push:
    branches:
      - master
      - main
      - 'release-*'

jobs:
  mri:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        ruby: ['2.4', '2.5', '2.6', '2.7', '3.0.0', '3.0.1', '3.0.2', '3.0.3', 'ruby-head']
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install
      - run: bundle exec rake

  jruby:
    strategy:
      matrix:
        os: [ubuntu]
        ruby: ['jruby-9.2.19.0', 'jruby-head']
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install
      - run: bundle exec rake

  truffle:
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu]
        ruby: ['truffleruby']
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install
      - run: bundle exec rake || echo "failed, but ignore it"
